language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "kVOlD9yKzlr5dZvYn5G8nzcjHBzF9iFMWTrp5pUqTUDSyLoohWiyWJPFo3x3jawT2H64D+2QAo5+6Lw89GzHckyRm8U7Ytb+ay8nvitRFhOWt0K2bZrlFD/lLvCfXqUNo1ibtQUSd+iPafzo0JAoBEym7222BQ9LaIciV2OZCLjFS9+V0ZqsI8HEH7M3qaP+jGHe5nXd2Vey09M/27a6782PjJ/a5m+Baj9EF3bnIL1SA7dT6WaDBEKv3erTVVjiaIzIzixh14T92qoK031GYVcQSr9C+XI7bX/Y0g4SGnBsUSVDv2IfHsn6nARorNLUsUMFWRhTf7TXItQaQDTk0vQzXGdat7f+Ow601K4mNe80/bQnB4SRXAqg/jE+5vjgPT8Wjgftc6xmws+yizWcwazB278TIHgt6vY+nxnBTsqvz8U+kaKgbwfHRPlRXGYyDPAtPIAMqOjCTdpgzbLnwJn/eJPMRtG/r9OrIu2VvtshgqiDVao665Uk+eBd2tU22mDdfHpW2e9Mp0T4A1lnG9rKEZwSG1QrPHMiJvFopOR90Yks3PFL7I76At6li6kg6AiEq8vxo6TaL9stfAs3eVmffLi/NU8BRKaTze9C5dgjyBPDcAu1HPxQddu145Glj/+oQNSwKKbhpoEnwnZLU9zgvsP5Af3cMeiPwHC1tKY="
  - secure: "fZGv2o0ixiKMyKFZW9NRRZu0cdgHnrECSGXi4wRFejQKJC2L/tSZ9wmisnxI6Tm8cgfltT6yivM/q+FylZlycU/ETB9MSNTxX752PinuD5b/6JhviqyatrZix9bp12FjykvfLPCtQcm9bsi3HKMPbUSdu6K+2LOi/aXhkUFV9Kle4YhDtUApPhDT2LZdtOOBKFGFM4Blw1vLTgy0ZElnfeDgtwScMG0L1PytV8rrychZgXCagaylNTheK35dHigL05yFDubUggKJGEoVaKDtcTV4p/f/KlyZTOkhQvkj8uFg4VTNcU7laZ0Sadq5JEDCQL44bODDvM+jFcvOHTZ+cBjXopxhdporlhDsyn7+vZlE6CjtdUAv9kkhw343ihgYeSdHt6kLDvcMuAqXUr1u42iaoCmdwFebiDKj1NkCTLPI5xkn2ONI4zQL8pPee3d3yfaz/ITTj5UUgePr07zJrsiekbZSpU8KBH13tvBzVBQxV8hHACYPu/nK6ZAmDUZKmZ9M05vjpTL4nPHfpjw4ixr7qJDbXL59onsarO5WXle+F1VUDNoG4/z6bmjwpqhbn8rHZejMWwPoGZfMqsLShfYfl7Nl3TWUMFxcC1G3HA7h8EUp/gwvFB7tRy+w2816pKa4i4Kn+DwCI/8VuX7B8SglPn0qI/MzyzPm/Td1Ykg="
  - secure: "suUgQioCFj+qxOBFCF+5juD2nYffKQRHGuplaxWWVA5a98yTzpaJXyqmp3VMEnSi750y79z9X5uUKTFBMTVOO2Un2bN05lKcKnGnoN1QEH0LWBBJaGtx3NzV7om9ol/+/SjuXsV3e24tBLBXcJTe191/qlKe99lMEyukymfvkWQqaMTzoZANhu3e5xBptbg+6fHLk+x+nWllgKLu6lWU9z6IZ3YszZciq4eZsgdHSp0F+MOZkpSM7CRP2ZwZyIcTCGOdq8cgYxLzNF1Qer4ykVMgMWGlGUmWNga8r6ZhH55jSJzKzHbN9gh3+1sZLU/0iKT0dZ+mB0sOlUXX9CWvsx+8EGTw+UMvWmrjp908YIbTVrARgY94dxLUHngP7FOVS20nhd5ulsGEopjhIWOtfyc1b8K8gI1vA1Ob479OV7/Amd8l2csw/ARBEwMy546b2Fv4aBw6iPxbOwC6j9AzwViTltKgYG5GSpsqG0qsP1laX1zZvhuwclES5Ezsl2bDeUTZBymLtXj5Bq38L6C0ye14W8+zxdj7Skty1a+s/kjoJYbyGXkZKXaFBBuO8G+AUzAvJ5QwYnT5lpiZk19ZUHWQhyTsGhpGmIvTgUhDi21c7bOfpoXpG7G8iiVochTqN3gwS5fe3cPOGKFnVGQw4o8ccuniiOq8e/SiNR7Oz8I="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_c93a2c334946_key -iv $encrypted_c93a2c334946_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi